### ISSUE TITLE
Feature Request: Version Number

### ISSUE THREAD

**Issue by ZV00** [AerialScreensaver/Aerial#1]
It would be great if Aerial Updater displayed a version number in the menu. Perhaps placing it next to the words "Aerial Updater" at the top of the menu?

**Comment by glouel** [comment]
Yeah it definitely needs to be somewhere in there. 

One thing I added in 0.4 is that I can ask you to upgrade the Updater (pointing you to the last release) from the manifest, in case there's a big bug fix or something. Hopefully when it's feature complete, there won't be a need to update it, or maybe once a year or two, that's what I'm shooting for right now !

**Comment by glouel** [comment]
So I haven't made a new release yet (see the discord) but I made an about box for the updater that brings the version number: 

![Capture d’écran 2020-08-03 à 22 01 43](https://user-images.githubusercontent.com/37544189/89222329-25f84780-d5d5-11ea-832d-62a53400cff8.png)

It's in the new Settings submenu, that also have the two new very wanted options, launch at startup and in the background: 

![Capture d’écran 2020-08-03 à 22 02 52](https://user-images.githubusercontent.com/37544189/89222354-2f81af80-d5d5-11ea-9a6d-6ec00b09c8f8.png)
 
Last thing, if for some reason there's a security issue/certificate change that would require you to update the Updater, you'll see this : 

![Capture d’écran 2020-08-03 à 22 05 14](https://user-images.githubusercontent.com/37544189/89222550-87201b00-d5d5-11ea-94db-93bdae3e8b5b.png)

I will not force update unless completely necessary, 0.5 will reflect those changes.

**Comment by glouel** [comment]
This is fixed 

![Capture d’écran 2020-08-18 à 10 39 11](https://user-images.githubusercontent.com/37544189/90490774-53013a00-e13f-11ea-8161-65f26c9c9100.jpg)
