### ISSUE TITLE
fan speed, CPU consumption

### ISSUE THREAD

**Issue by jgiblin1** [AerialScreensaver/Aerial#10]
Hi Guillaume,

Love this app. Recently noticed very high fan speeds since updating to 2.02. Of note, I'm running on mid 2012 MacBook Air which is likely culprit, though seemed fine prior to update. Tried to set cache limit at 4GB, running vids at 1080p H264. Anything else you'd recommend, aside from getting a new computer of course

Thanks

**Comment by ZV00** [comment]
Hey @jgiblin1, 

This may be expected when you first use Aerial 2.0 and any time it is downloading videos (if you have automatic cache set). It should resolve over time and/or after a computer restart. 

You can cache your videos in advance (and set the cache to not automatically rotate) if the increase fan speeds are concerning to you.

**Comment by glouel** [comment]
Hi @jgiblin1 

Please try 2.0.5 I think I fixed a performance issue there. Please let me know!

**Comment by jgiblin1** [comment]
It works perfectly! Thank you!

**Comment by glouel** [comment]
Thanks for confirming and apologies for not answering earlier looks like I mistakenly un watched my own repository 🙈
