### ISSUE TITLE
Feature Request: Dark mode menu bar icon

### ISSUE THREAD

**Issue by ahenriksen-inferno** [AerialScreensaver/Aerial#12]
First of all, thank you so much for making this app! It's a huge timesaver for me. My request is for a dark mode (white) menu bar icon. I was thinking at rest, it could be all white and then when an update is available, show some color. I would be more than happy to help with the design for this if you'd like.

**Comment by glouel** [comment]
Hey there! 

I'm teeeeerrible at design so I definitely, definitely welcome any bit of help! 

I don't know if you've seen Big Sur yet but Apple went with lines (or quite probably, SF Symbols):

<img width="288" alt="Capture d’écran 2020-08-30 à 23 55 37" src="https://user-images.githubusercontent.com/37544189/91670288-4f48bc80-eb1c-11ea-8b20-6baccce4ea75.png">

Those get white or black depending on desktop background (which is a bit weird). In a way it's a good style that would fit what you're asking but I have no idea how hard it would be to get something like that going. Technically I think those are 48px or 44px by size but you may want to double check that.

Thanks and let me know if I can assist you in some way.

**Comment by ahenriksen-inferno** [comment]
I'm happy to help! I'm running Big Sur on my laptop and think we can match the style. I'll look into the specs and make sure to follow them.

**Comment by ahenriksen-inferno** [comment]
@glouel I'm still working on this. I didn't want you to thing I forgot or bailed on you.

**Comment by glouel** [comment]
@inferno-adam no worries ! Thanks for the update but take your time !

**Comment by ahenriksen-inferno** [comment]
@glouel would it be possible to email you instead? Much easier for me to share files and stuff. My email address is ahenriksen[at]infernodesign[dot]com.

**Comment by TedTschopp** [comment]
Here is something I whacked together.  I don't know how good it will look as I can't get it running on my machine.  I'll try more when I have more time.

[Icons.zip](https://github.com/glouel/AerialCompanion/files/5556547/Icons.zip)

**Comment by glouel** [comment]
Hey @TedTschopp sorry I missed your post, I did release Companion 1.2 in the meantime with the icon designed by @inferno-adam, you can check it out here : https://aerialscreensaver.github.io/index.html (there's a screenshot at the bottom). 

Apologies for missing yours.

**Comment by TedTschopp** [comment]
No worries... I look forward to the "bug" being "fixed" instead of seeing my work in production.  Thanks!
