### ISSUE TITLE
Feature Request: Hide Menubar Icon

### ISSUE THREAD

**Issue by alexpersian** [AerialScreensaver/Aerial#13]
First off, love this program. I've been using it for years and love that the support has continued. Thank you!

With the new Aerial Updater I noticed it adds a menubar icon for quick access. For the life of me I wasn't able to find an option for hiding that icon within the settings though. Would it be possible to add that functionality?

**Comment by ZV00** [comment]
Hey @alexpersian,

This guide will walk you through how to run it in the background and get it out of your menu bar: https://aerialscreensaver.github.io/faq.html#AerialCompanion

**Comment by alexpersian** [comment]
Ahh I see. I had that option selected but must have to go through a restart cycle for it to take effect. 

![image](https://user-images.githubusercontent.com/5446451/94446929-3f51e600-0177-11eb-85b9-469a77d11b75.png)

**Comment by glouel** [comment]
Yep or just quitting, you should be fine now !

**Comment by ZV00** [comment]
> Ahh I see. I had that option selected but must have to go through a restart cycle for it to take effect.
> 
> ![image](https://user-images.githubusercontent.com/5446451/94446929-3f51e600-0177-11eb-85b9-469a77d11b75.png)

No worries! Glad it is working for you now!

**Comment by alexpersian** [comment]
Appreciate the help. I'll close this issue.
