### ISSUE TITLE
Screensaver flat out doesn't work on iMac Pro

### ISSUE THREAD

**Issue by name99-org** [AerialScreensaver/Aerial#15]
Just FYI the current version (Installer 1.1, ScreenSaver 2.1.0) just doesn't work on an iMac Pro running Mojave 10.14.6
The screensaver does not launch when the machine is quiescent, and when you Open Preferences/Desktop&Screensaver/ScreenSaver and pick Aerial, the window goes grey and nothing is display. 

Aerial used to work on this machine/OS, up till maybe 3 or 4 months ago. I can't be sure exactly when it broke because I moved house at that time and for two months life was very chaotic and I wasn't in a position to notice that my Mac wasn't behaving exactly as normal. 
<img width="670" alt="Screen Shot 2020-09-28 at 7 11 44 PM" src="https://user-images.githubusercontent.com/64371307/94504807-80b9b400-01be-11eb-9cfc-3f0ee2a7b911.png">

**Comment by ZV00** [comment]
Hey @name99-org,

This is a known issue that is outside the control of @glouel, it has to do with a 10.14.6 security patch that was released that broke *all third party* screen savers. You can find additional details on this issue here: https://github.com/JohnCoates/Aerial/issues/1107

**Comment by MarcelProust** [comment]
I have this issue on a late 2015 iMac running 10.14.6. Presume @ZV00 means the patch ‘broke all _third party_ screensavers’?

Runs fine on the execrable Catalina.

**Comment by glouel** [comment]
Yep exactly, Apple pulled their patches yesterday, see this thread here for more info : https://github.com/JohnCoates/Aerial/issues/1107

It also broke some of Apple's screensavers apparently (the pictures one) according to that site. To be very precise then, it broke _Swift_ screensavers ;) 

https://mrmacintosh.com/mojave-2020-005-security-update-causing-major-problems-updated/

**Comment by glouel** [comment]
This has been fixed for a while and I forgot to close this sorry ;)
