### ISSUE TITLE
Update Arial shows when launching arial full screen on one monitor

### ISSUE THREAD

**Issue by ikonted** [AerialScreensaver/Aerial#22]
It shows that the version of arial installed on my mac is 2.0.10 whereas in the arial companion it says 2.2.6. It leads me to believe that different types of screen savers are used here.
Also it shows the clock which i don't want to, would be good if this launch screen has the same settings as my screen saver

**Comment by glouel** [comment]
Hey there, is that just after updating ? Try fully closing System Preferences and opening it again. System Preferences will not reload the new version after install (but the screensaver when it runs, is the new version). Let me know if that fixes it !

**Comment by ikonted** [comment]
It worked, it still shows the time though, for other releases i would use the same settings as the original screen saver.
