### ISSUE TITLE
Install Now of Update gives SSL error

### ISSUE THREAD

**Issue by uromahn** [AerialScreensaver/Aerial#26]
I am trying to update Aerial to the latest version using the AerialCompanion.
However, when initiating the update manually, I am seeing the following error message:

**Installation error**

Error: An SSL error has occurred and a secure connection to the server cannot be made.

Please report.)

This error is usually happening when downloading from GitHub over https but then the download redirects to a different URL with a domain name that is not part of the SSL certificate!

**Comment by glouel** [comment]
Hey @uromahn 

This is weird. I'll do a check here in a minute but are you by any chance behind some sort of entreprise proxy or something of the kind ? 

Edit : I did a check here, updating to 2.3.2 and that worked fine so I'm wondering. It's possible a server from GitHub had a certificate issue too, though unlikely.

**Comment by glouel** [comment]
Please reopen if you still experience the issue.
