### ISSUE TITLE
Spelling Error in the about menu.

### ISSUE THREAD

**Issue by jake01756** [AerialScreensaver/Aerial#3]
It should be *developed*, not *developped*.

Screenshot: 
![about window](https://user-images.githubusercontent.com/28026633/90058861-451b6700-dcb0-11ea-8a18-6d3b03a84603.png)

**Comment by glouel** [comment]
Hi @jake01756 

Sorry for the late reply, thanks for the report I fixed it for next build which will be out later today.

**Comment by jake01756** [comment]
Ok thanks. I'll close the issue.
