### ISSUE TITLE
Request: Option to remove icon from top menu bar

### ISSUE THREAD

**Issue by eoren1** [AerialScreensaver/Aerial#30]
On new MacBook Pro and would appreciate a way to keep the icon out of the top menu given the limited space available with the notch

**Comment by kg-currenxie** [comment]
Was coming here to post the same. Please! :)

**Comment by glouel** [comment]
Looks like I missed the original post so apologies to @eoren1 

But to both : you can already do that, it asks you during setup if you want to have it run in the background (so it doesn't show up in the menu bar) or not. Maybe my explanations on that screen aren't clear, so I'm more than open to feedback to improve that.

Anyway, it's an easy fix, pick this :
 
<img width="475" alt="Capture d’écran 2021-11-23 à 13 07 00" src="https://user-images.githubusercontent.com/37544189/143021387-f7bb4955-827c-4e0e-a181-bbcb10641227.png">

When you click that option, you'll see that (which I think is self explanatory but again, welcoming feedback) : 

<img width="277" alt="Capture d’écran 2021-11-23 à 13 08 08" src="https://user-images.githubusercontent.com/37544189/143021499-3e1d7619-15a0-4283-8d32-f47bff58b643.png">
 
I think the menu maybe has too many options and would be better served by a window or something, or maybe the launch option doesn't make sense and I should just have a top level thing for not showing in menu bar. I'll have to keep thinking about it.

Again sorry for missing the original issue !

**Comment by kg-currenxie** [comment]
Oh great. Totally missed that menu option for some reason 😅  <3
