### ISSUE TITLE
Feature request: Play the same video on multiple screens

### ISSUE THREAD

**Issue by WetTiger** [AerialScreensaver/Aerial#32]
Hi,
I am using multiple screen in my setup and it would be great if once Aerial comes on, it would play the same video on both/all screens synchronous.
Is there or will there be such an option?
Many thanks for your work!

**Comment by glouel** [comment]
Hey @WetTiger 

There sure is, check the Displays options here :

![Capture d’écran 2022-01-19 à 17 08 58](https://user-images.githubusercontent.com/37544189/150169894-7b54f75b-bdcf-497d-9232-2c98500cf783.jpg)

You can also span one video on multiple monitors. 

Take care

**Comment by WetTiger** [comment]
Hi @glouel,
thx for the quick reply. Now i found it. Had to pull the window bigger, wasnt able to scroll through it.
Love it!
