### ISSUE TITLE
Issue : v3.0.2 "Options" not accessible anymore

### ISSUE THREAD

**Issue by DiAnSk64** [AerialScreensaver/Aerial#33]

**Comment by DiAnSk64** [comment]
I installed v3.0.2 on a iMac 21" running under Catalina 10.15.7, and after trying to download a few iOS 15 screensavers, the menu options stopped working : I quit the control panel, reopened it, but now the "Options" button for AC 3.0.2 is not working anymore.
What can I do to access the settings again ?

**Comment by glouel** [comment]
We're talking about the button below the tiny preview right ?
 
Did you try closing down System Preferences entirely, with Aerial selected first ? Sometimes a reboot helps too on Catalina, things tend to get stuck on that OS. 

Also switching from multiple screensavers can cause that on Catalina, so close with Aerial selected (or the one you want to use) and reopen usually does the trick.

**Comment by glouel** [comment]
Closing this, please reopen if you still need assistance
