### ISSUE TITLE
I don't had the picture... 

### ISSUE THREAD

**Issue by zukaC** [AerialScreensaver/Aerial#36]
[https://imgur.com/ATe6l8U](url)
I don't know whats going on,I don't had the picture... someone can help?

**Comment by zukaC** [comment]
`<a href="https://imgur.com/ATe6l8U"><img src="https://i.imgur.com/ATe6l8U.png" title="source: imgur.com" /></a>`

**Comment by glouel** [comment]
Hi @zukaC 

Close System Preferences then open Terminal and paste this : 

```defaults delete ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist```

Then you should be ok.

**Comment by zukaC** [comment]
@glouel Thank you very much!! It can be used normally!

Wishing you good wealth and prosperity!
