### ISSUE TITLE
Companion 1.4.0b1 not recognising Aerial 3.0.8b1 is installed

### ISSUE THREAD

**Issue by wakco** [AerialScreensaver/Aerial#37]
After successfully installing the update, Companion continues to think there is an update available.

The only question is, is this an Aerial issue with how it's version is being reported, or a Companion issue with how it is checking the version installed vs. what updates are available?

**Comment by glouel** [comment]
Hey, sorry about that one, I can confirm the issue. 

I upgraded my mac and must have messed something up doing the beta release on the new one, I'll have a look.

**Comment by wakco** [comment]
If it helps I have both Intel and Apple Silicon Macs, and the issue appeared on both. I should also note, that until I upgraded when I discovered the issue, the Intel one was using Companion version 1.2.2, which also had this update issue. (I should have put this in the initial post, but failed to think that far into it, at the time).

**Comment by megaroeny** [comment]
Same here. Tried a few times and restarting the app, no luck. 😕

**Comment by glouel** [comment]
Sorry everyone, this should be fixed, you'll be prompted to get Aerial 3.0.8beta2 and it will stick now.
