### ISSUE TITLE
Installation Error "Could not copy .saver"

### ISSUE THREAD

**Issue by SamTheGeek** [AerialScreensaver/Aerial#4]
When attempting to install the screen saver I repeatedly receive an error that it can't be copied.

<img width="420" alt="Screen Shot 2020-08-20 at 3 32 00 PM" src="https://user-images.githubusercontent.com/2694459/90816482-58ef4a80-e2fa-11ea-914f-dfdc2db2377b.png">

**Comment by PaulBartelings** [comment]
I have the same error, I'm running this on BigSur Beta 5.

Hope you can help us ;)

**Comment by glouel** [comment]
Hey there, sorry about that one I completely missed the notification ! 

@SamTheGeek and @PaulBartelings 

Can you confirm a couple of things : 
- Did you put Aerial.app in Applications or somewhere else ?
- Which version of macOS are you using ?

I'll try to get back to you asap.

**Comment by dscoti** [comment]
I have the same problem when installing the plug-in from the companion app.
I'm running Catalina 10.15.6. I haven't tried it yet on my Big Sur beta machine.

If I recall correctly, I attempted to install aerial.saver and got the dialog to delete the existing .saver from the library. I did so and installed. Then I ran the aerialinstaller.dmg and put the aerial.app in the applications folder.
I now have a red triangle over the Aerial menu bar icon. Attached and sorry about the resolution.

Could it be the order in which I installed the aerial.saver and companion app?

I love the option for the community videos. They are really great.

Thanks for your hard work!
![Screen Shot 2020-08-21 at 3 40 06 PM](https://user-images.githubusercontent.com/70039917/90941044-d0d67700-e3c5-11ea-9df0-b00fc31b2bed.jpg)

**Comment by glouel** [comment]
Hey @dscoti and apologies to the others before @SamTheGeek and @PaulBartelings, I was doing so many things at the same time earlier that I completely misread the bug and mixed it up with another one :( 

So, to fix that, if you know how to handle Terminal, please try this: 
```
cd ~/Library/
mkdir "Screen Savers"
```

Then you'll be able to install. 

It looks like I completely misunderstood something about how this directory should be created already. I'll fix the installer tomorrow, sorry about that one.

And glad to hear you enjoy the videos by Josh & Hal, they were super nice to share them with the project and worked hard to adapt them adding descriptions and stuff so they'd feel right at home in Aerial. They do have more videos available fyi, click the more button next to their source to check them out ;)

**Comment by dscoti** [comment]
Thanks for the prompt reply. 

I created the directory and it still failed. I'm sure I've done something incorrectly. I'm not a wizard in Terminal, but I get by.

This is my output in /Library/Screen Savers
![Screen Shot 2020-08-21 at 4 46 39 PM](https://user-images.githubusercontent.com/70039917/90943364-8c9ba480-e3ce-11ea-817a-cef508c51390.jpg)

I guess I should just wait until you drop the new installer.  :-)

**Comment by glouel** [comment]
So there's  no ~ in your screenshot and that's bugging me

`/Library` and `~/Library` are different, one is the global one, the second is for your user, so if it's Dana, like, `/Users/Dana/Library`.

So make sure you're creating the correct one, for your own user.

**Comment by dscoti** [comment]
I did use the ~/Library command, it just didn't show that way when I 

Of course, I cannot do anything with the global /Library.

So...I did some checking and realized that in my user library it or I had created two separate folders /Library/Savers and /Library/Screen. 

I renamed one of the folders to /Library/Screen Savers and installed the app.

I guess I typed something wrong. 

It's working now. 

Thanks for your patience.

**Comment by dscoti** [comment]
Finally, Here's a screenshot of both /Library and ~/Library with the resulting prompt.

![Screen Shot 2020-08-21 at 5 50 03 PM](https://user-images.githubusercontent.com/70039917/90944999-fd46bf00-e3d6-11ea-9d8f-3f1060703d2f.jpg)

**Comment by glouel** [comment]
Awesome, and sorry I was confused about the path, I'm used to having the tilde in my prompt as I use iTerm, so that's why I didn't get it. Regarding the two directories, you need to put between quotes when there's a space, so 

```
mkdir "Screen Savers" 
```
is the way !

For @SamTheGeek and @PaulBartelings, sorry to have made you wait, here's version 1.0.1 with the fix : https://github.com/glouel/AerialCompanion/releases/tag/v1.0.1

Thanks for your patience and sorry to have made you wait

**Comment by dscoti** [comment]
Not a problem. Like I said, I’m not great with Terminal, but not afraid to try. 

I didn’t remember to use quotes the first time. 
Also, I believe you can use mkdir Screen\ Savers to accomplish it as well.

However, it was my mistake and a reminder/learning experience for me.

Dana Scott
dscoti@me.com
