### ISSUE TITLE
kernel panic when using aerialcompanion

### ISSUE THREAD

**Issue by Bradley-Liu** [AerialScreensaver/Aerial#43]
macos 12.5.1 
intel uhd630 igpu
dgup rx560d
I got a kernel panic when screen savor run for about 15mins. sleep is disabled through system settings. panic info is below. please help.

panic(cpu 3 caller 0xffffff8018d7999f): userspace watchdog timeout: no successful checkins from WindowServer in 120 seconds
service: logd, total successful checkins since load (1640 seconds ago): 165, last successful checkin: 0 seconds ago
service: WindowServer, total successful checkins since load (1610 seconds ago): 149, last successful checkin: 120 seconds ago
service: opendirectoryd, total successful checkins since load (1640 seconds ago): 164, last successful checkin: 0 seconds ago

Panicked task 0xffffff8b71701d10: 3 threads: pid 126: watchdogd
Backtrace (CPU 3), panicked thread: 0xffffff86a4bf7540, Frame : Return Address
0xffffffeaec573690 : 0xffffff801587fd6d mach_kernel : _handle_debugger_trap + 0x41d
0xffffffeaec5736e0 : 0xffffff80159e1086 mach_kernel : _kdp_i386_trap + 0x116
0xffffffeaec573720 : 0xffffff80159d03f3 mach_kernel : _kernel_trap + 0x4d3
0xffffffeaec573770 : 0xffffff801581fa70 mach_kernel : _return_from_trap + 0xe0
0xffffffeaec573790 : 0xffffff801588013d mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffeaec5738b0 : 0xffffff801587f8f6 mach_kernel : _panic_trap_to_debugger + 0x2b6
0xffffffeaec573910 : 0xffffff8016114ec3 mach_kernel : _panic_with_options + 0x89
0xffffffeaec573a00 : 0xffffff8018d7999f com.apple.driver.watchdog : __ZN10IOWatchdog14userspacePanicEP8OSObjectPvP25IOExternalMethodArguments.cold.1 + 0x27
0xffffffeaec573a10 : 0xffffff8018d795f2 com.apple.driver.watchdog : __ZN10IOWatchdog35userspaceDisableUserspaceMonitoringEP8OSObjectPvP25IOExternalMethodArguments
0xffffffeaec573a30 : 0xffffff8018d78971 com.apple.driver.watchdog : __ZN20IOWatchdogUserClient14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x7f
0xffffffeaec573b60 : 0xffffff801608365c mach_kernel : _is_io_connect_method + 0x42c
0xffffffeaec573cc0 : 0xffffff8015986d86 mach_kernel : _iokit_server_routine + 0x4f56
0xffffffeaec573dd0 : 0xffffff801585a9ab mach_kernel : _ipc_kmsg_send + 0x46b
0xffffffeaec573e60 : 0xffffff80158711a9 mach_kernel : _mach_msg_overwrite_trap + 0x2c9
0xffffffeaec573ef0 : 0xffffff80159b305a mach_kernel : _mach_call_munger64 + 0x1ea
0xffffffeaec573fa0 : 0xffffff8015820256 mach_kernel : _hndl_mach_scall64 + 0x16
      Kernel Extensions in backtrace:
         com.apple.driver.watchdog(1.0)[8BE4EE7F-9150-3161-BE84-36874BF82DE2]@0xffffff8018d77000->0xffffff8018d79fff

Process name corresponding to current thread (0xffffff86a4bf7540): watchdogd
Boot args: keepsyms=1 debug=0x100 alcid=11

Mac OS version:
21G83

Kernel version:
Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64
Kernel UUID: D0DC2052-71F4-3DCB-B189-BEE5A59B3B42
KernelCache slide: 0x0000000015600000
KernelCache base:  0xffffff8015800000
Kernel slide:      0x0000000015610000
Kernel text base:  0xffffff8015810000
__HIB  text base: 0xffffff8015700000
System model name: iMac19,1 (Mac-AA95B1DDAB278B95)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 1642968896872
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000017e8893da0a
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000a2ed4f534 0x0000000000000000
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff803aa4e000 - 0xffffffa03aa4e000
  . PGZ   : 0xffffff803aa4e000 - 0xffffff803ea4f000
  . VM    : 0xffffff803ea4f000 - 0xffffff850ad82000
  . RO    : 0xffffff850ad82000 - 0xffffff86a43e8000
  . GEN0  : 0xffffff86a43e8000 - 0xffffff8b7071b000
  . GEN1  : 0xffffff8b7071b000 - 0xffffff903ca4e000
  . GEN2  : 0xffffff903ca4e000 - 0xffffff9508d81000
  . GEN3  : 0xffffff9508d81000 - 0xffffff99d50b4000
  . DATA  : 0xffffff99d50b4000 - 0xffffffa03aa4e000
  Metadata: 0xffffffa03b25e000 - 0xffffffa05b25e000
  Bitmaps : 0xffffffa05b25e000 - 0xffffffa06725e000

**Comment by Bradley-Liu** [comment]
It has nothing to do with video decoding. I play cached videos in a loop with quicktime.  macos never panics when playing.
It has something to do with the screen savor program.

**Comment by glouel** [comment]
Hey @Bradley-Liu
 
Did you report to Apple ? Userspace should never be able to crash Kernel, so this is something they definitely need to see. `watchdogd` seems to be the culprit and I see a lot of people having issues with Final Cut Pro, so it's probably video decoding related in some way (perhaps hardware decoding/eGPU), it's likely also sleep/restart related. See this thread for some suggestions first, but I'm afraid there's not much I can do besides that : https://old.reddit.com/r/MacOS/comments/hwk0o5/how_to_stop_watchdog_timeout_kernel_panics/

Definitely send a feedback to Apple with your crash.

**Comment by Bradley-Liu** [comment]
NO I didn't send it to apple. I am using a hackintosh actually. I don't know if the report will be useful to apple or not.
Before this. I use igup only and everything is fine. Recently I updated my machine with a dgpu(rx560). After that, the KP started to happen. I've changed to 1080p hevc resolution and this does solve the problem. But I've got a 4k monitor. Playing  1080p videos on a 4k monitor sucks. If there is something wrong with HW decoding it would also crash my maching when using 1080p hevc. Really weired. I've been testing it with 4k hevc movies recently with vlc player. This never crashes my machine.

**Comment by glouel** [comment]
You can't compare Aerial playback with whatever VLC is doing, it has very limited support for hardware decoding as Apple is not opening most of those paths, and that's on a real mac. 

The best way to emulate what Aerial does is to play a video, from its cache (and not just some random 4K video), in Quicktime.  

But in all cases, there's literally nothing I can do for you. Kernel panics are a problem for Apple, or more probably in your case, with the distributor of your patch set for your hackintosh. You are more likely to find relevant help from the OpenCore people (assuming this is what you are running), as it's likely a patch and/or driver issue. 

Best of luck to you on getting help but I can't do anything, so closing this.
