### ISSUE TITLE
Playback is narrow with second display.

### ISSUE THREAD

**Issue by jridder** [AerialScreensaver/Aerial#44]
I have noticed recently that playback get cut off to a smaller size with 2 screens. M1 Pro MacBook Pro. macOS Ventura Build 22A5331f.
![IMG_1582](https://user-images.githubusercontent.com/11082465/188324889-010b6cc4-8725-4ef4-afb7-c2db8913fe5a.jpeg)

**Comment by glouel** [comment]
Hey @jridder 

It looks like the video is probably rotated on your left screen for some reason, this is excessively weird. Can you go into advanced, enable debug mode, launch the screensaver once, then send me the log ?

Not sure if it's a ventura thing or if it's something else, but the width looks like the correct height, just that the video is wrongly rotated (but not the overlays)... weird one !

**Comment by jridder** [comment]
I didn't even notice the rotation until you said that. I just had seen the issue out of the corner of my eye this morning when walking by my office. Log attached. 
[AerialLog.txt](https://github.com/AerialScreensaver/AerialCompanion/files/9485123/AerialLog.txt)

**Comment by glouel** [comment]
Thanks, the display detection looks ok from what I can see, so it's likely some weird bug with the video. I'll try to replicate that setup on Ventura this week and keep you posted.

**Comment by jridder** [comment]
Did you implement a fix? The reason I ask is it seems to be working correctly now.

**Comment by glouel** [comment]
Hey @jridder 

Sorry I completely forgot to update you. 

I think the bug was with the latest macOS SDK. 3.1.3 is using the "old" monterey SDK which fixes many many issues so for the time being I'll be using it. It has the side effect to fixing this bug too it seems.

I'll stick to the old xcode version for the foreseeable future

**Comment by jridder** [comment]
Closed for now, thanks!!
