### ISSUE TITLE
Error/typo in the cache is full screen

### ISSUE THREAD

**Issue by drewbombard** [AerialScreensaver/Aerial#45]
Looks like there is a small bug in the warning message when the cache is nearly full.

It says:
> Your cache limit is currently set to 5.0 GB, and current contains (**_Function_**) of files.

**Comment by glouel** [comment]
@drewbombard can you make a screenshot ? I'm not sure exactly where you see this text. Thanks for the report in any case !

**Comment by drewbombard** [comment]
Oops... yeah, I meant to send this with the original post:

![Screen Shot 2022-09-20 at 9 52 48 AM](https://user-images.githubusercontent.com/293224/191293198-c89cc2e9-30b4-4f5b-baa6-2cac977daaa9.png)

**Comment by glouel** [comment]
No problem ! 

I'll have a look tonight, I did move some stuff around so it's probably that, thanks again for the report I'll keep you posted.

**Comment by glouel** [comment]
<img width="372" alt="Capture d’écran 2022-09-20 à 18 38 36" src="https://user-images.githubusercontent.com/37544189/191315386-c9e2eb45-4508-47ba-b696-f95ae8f93d90.png">

This is fixed for next version, I won't release it today though but soon. Again thanks for the report!
