### ISSUE TITLE
Even though I have multiple videos selected it just loops on the first one

### ISSUE THREAD

**Issue by mrolfer** [AerialScreensaver/Aerial#46]
Not sure why the dropdown shows 1.2.2 and Installed as 3.1.3

![Capto_Capture 2022-10-10_10-55-37_AM](https://user-images.githubusercontent.com/6589075/194926352-b5707576-460a-43fd-9a87-a063cd2a3eeb.jpg)
![Screen Shot 2022-10-10 at 10 56 46 AM](https://user-images.githubusercontent.com/6589075/194926772-b6fa5155-d048-4072-8987-f6c39bf9dc80.jpg)

**Comment by glouel** [comment]
There are two parts to Aerial, the Screen Saver itself (3.1.3) and the installer/auto updater (Companion, which you have in 1.2.2). 

Regarding your title, did you enable automatic downloads or not ? If you disable automatic download, you are likely to get stuck with one video.

**Comment by glouel** [comment]
Please reopen if you still need assistance
