### ISSUE TITLE
Bring back the old UI :-)

### ISSUE THREAD

**Issue by n0rt0nthec4t** [AerialScreensaver/Aerial#48]
Been testing the beta's of the Aerial Companion and the more use I have, definitely feels like a major regression for the UI in 1.5B.

**Comment by brian163** [comment]
I dunno, I kind of like it. ;-) I feel it is an interesting design choice not to put text labels on the various button options. But once I paid attention to the hover over tips explaining what each button was for I was immediately less confused.

**Comment by n0rt0nthec4t** [comment]
Guess my issue is its "Not macOS like" and more like the bundled vendor utilities you get on a Windows PC that can't wait to remove!
