### ISSUE TITLE
1.5.0b2 download

### ISSUE THREAD

**Issue by brian163** [AerialScreensaver/Aerial#49]
When I download [Aerial.Companion.app.zip](https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.5.0b2/Aerial.Companion.app.zip) from the 1.5.0b1 assets section both the Finder and app versions still show as 1.5.0b1 ?

**Comment by glouel** [comment]
Yes yes, it says beta1, I messed up the file but it's really beta2  !

**Comment by brian163** [comment]
Thanks for confirming.
