### ISSUE TITLE
Constant notifications of `Background Apps Added` in Ventura

### ISSUE THREAD

**Issue by JerryWu96** [AerialScreensaver/Aerial#51]
Hi Aerial devs,

### Symptoms
First of all, thank you so much for the great work - I really, really enjoy using this app.

However after upgrading to macOS Ventura 13.1, I keep getting [notification pop-ups](https://ibb.co/yn6wNXg) daily at random time, when the screensaver is running in the background.

I use the mode that the app icon is seen in the menu bar. I have also [allowed the background item](https://ibb.co/51MTJ8f) in System Settings / General / Login Items, but this doesn't resolve this issue.

### Request
Could you investigate and provide a fix or a solution to this issue?

Someone claimed it might be caused by a [code signing issue on reddit](https://www.reddit.com/r/MacOSBeta/comments/yecvhm/comment/j0h8roz/?utm_source=reddit&utm_medium=web2x&context=3), but not sure if this is the case.

Thanks and happy holidays!

**Comment by glouel** [comment]
Hey @JerryWu96  

Thanks for the report, someone asked about this like 2 minutes ago here : https://github.com/AerialScreensaver/AerialCompanion/issues/47#issuecomment-1361637173

Your link is super interesting thanks, as I said in the other comment, I'll try to dig into it next week as I have some vacation time. 

Aerial & Aerial Companion are both signed and notarized, so maybe it's more an issue of which SDK it's signed with. I'll keep you posted.

**Comment by glouel** [comment]
@JerryWu96 

I believe I managed to fix this one by recompiling with the latest Xcode + SDK for Ventura. Can you try this version : https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.5.0b3/Aerial.Companion.app.zip

It's in a zip, so unzip and move to your applications folder. You may need to go into the settings (at the bottom) and set to manually then reset to background so the login item is reinstalled. I don't think it's required but just in case. 

I don't get the error anymore here with Ventura 13.2a beta for Aerial Companion (but still get it for VMware Fusion). 

Let me know when you can.

**Comment by JerryWu96** [comment]
@glouel Sorry for the late reply. I just got my laptop back and installed this beta. 

>  You may need to go into the settings (at the bottom) and set to manually then reset to background so the login item is reinstalled

Could you elaborate a bit more on this part? Did you mean the Aerial settings, or system settings? 
I am also confused by `set to manually then reset to background`. What does this mean?
Currently overwriting the stable version with this beta does not re-install the login item, so I'd love to get some further clarifications. Thank you!

**Comment by glouel** [comment]
Yeah sorry that was a bit cryptic !

Press that button on the bottom to open Companion settings : 
<img width="509" alt="Capture d’écran 2023-01-19 à 17 28 38" src="https://user-images.githubusercontent.com/37544189/213498487-6b8d6d9d-cada-4452-8966-8fcf546933a7.png">

This will open a new window, at the bottom you have this setting : 
<img width="475" alt="Capture d’écran 2023-01-19 à 17 28 57" src="https://user-images.githubusercontent.com/37544189/213498719-00912deb-ff9b-4af0-9de6-04d3c267f501.png">

So here, set to "Manual" first (this will uninstall the old launch item).

Then set to "At startup" (it will reinstall in a way that Ventura seems to like better).

You will get one more of these boxes at your next reboot, but subsequent reboots will be fine.

**Comment by JerryWu96** [comment]
@glouel Thank you for the instructions! Yes I could confirm that I no longer see any pop ups showing up. 

Maybe in the future you could look into making the naming of the login item more meaningful, instead of the new mechanism that gives the dev's name (Guillaume Louel), which is really not ideal for users. 

Thanks again for your time in fixing this!
