### ISSUE TITLE
aerial update?!

### ISSUE THREAD

**Issue by emmgr23** [AerialScreensaver/Aerial#52]
does the development of aerial stoped ?

**Comment by glouel** [comment]
uh ?

Latest Aerial (screensaver) was released 9 days ago, version 3.2.3 : https://github.com/JohnCoates/Aerial/releases/tag/v3.2.3

Latest Aerial Companion (auto updater + extra features) beta was about a month ago : https://github.com/AerialScreensaver/AerialCompanion/releases/tag/v1.5.0b3

**Comment by emmgr23** [comment]
sorry i wanted to say aerial companion the last one was 1.2.2
thanks for the reply :)
i love this app so much

**Comment by glouel** [comment]
No prob, try the 1.5 beta !
