### ISSUE TITLE
Aerial Not Launching

### ISSUE THREAD

**Issue by markmaly8** [AerialScreensaver/Aerial#53]
Not sure whats going on, but for some reason I downloaded the beta version for Ventura but anytime I try to launch it, nothing happens?

**Comment by glouel** [comment]
Hey @markmaly8 

You should see the icon in your menu bar :
 
<img width="627" alt="Capture d’écran 2023-02-20 à 16 58 49" src="https://user-images.githubusercontent.com/37544189/220153159-66a8c341-abb9-4df1-b0e0-7cb84ff15c08.png">

Isn't it there ?

**Comment by markmaly8** [comment]
Wow sorry, I see it. Thank you for the quick response! It was a small issue on my side that was resolved by restarting my computer. Is there anyway to change the orientation of the videos so they play on a vertical tv that is hooked up to an apple tv?

My ultimate goal was to be able to add these videos to my "Photos" app on my mac in a shared folder, change the orientation to vertical, then these would be able to be displayed on our vertical tv and be oriented the correct way.

**Comment by glouel** [comment]
I'm not sure I understand the Apple TV part. AFAIK if you plug an Apple TV it will show up always in landscape mode (horizontal), and you can't set it up for portrait mode (vertical). Because of this the default screensaver on the Apple TV will always show its videos on the side. 

I'm sure you can use an app like VLC or something though to rotate the videos directly on the Apple TV during playback ?

**Comment by markmaly8** [comment]
Thanks for the recommendation on VLC. Where can I find the actual locations of the videos from the app on my computer?

**Comment by glouel** [comment]
Go to Aerial's screen saver settings in System Settings, then Cache > Show in Finder

**Comment by markmaly8** [comment]
Forgive me, Im new to this platform and don't know how to direct message you? Would like to discuss hiring you to help me out with a project if you are open to it. Let me know the best way to reach out to you.

**Comment by glouel** [comment]
There's no direct message on github, you can send me an email at

**Comment by markmaly8** [comment]
FYI I sent over an email, let me know if you got it.
