### ISSUE TITLE
The two monitors do not display the screensaver correctly

### ISSUE THREAD

**Issue by yangsss717** [AerialScreensaver/Aerial#56]
After updating to MacOS 13.3, using two monitors will cause the screen saver to display incorrectly.
![WechatIMG26](https://user-images.githubusercontent.com/34479436/229465675-ce05ec86-4577-4d54-a4d5-b8f6c820334e.jpeg)

**Comment by glouel** [comment]
Hi @yangsss717 

Yes sadly there's a bug in macOS Ventura 13.3. Apple fixed it in upcoming 13.4beta1 if you have access to it. More information here : https://github.com/JohnCoates/Aerial/issues/1286

**Comment by LonePheasantWarrior** [comment]
I also encountered this error
I have two screens. My setting is "play screen saver on all screens", but only the attached screen has images, the main screen is dark.

My device is a macmini with m2 chip

**Comment by glouel** [comment]
@LonePheasantWarrior see this link https://github.com/JohnCoates/Aerial/issues/1286, the bug for 2 screens will be mostly fixed in macOS 13.4 which should be out this week, maybe later today/tomorrow.

**Comment by LonePheasantWarrior** [comment]
> 

Okay, thanks XD

**Comment by pudge** [comment]
It does not appear to be fixed in 13.4. Aerial worked fine for me with three monitors until 13.4.

https://github.com/JohnCoates/Aerial/issues/1286#issuecomment-1553783410

**Comment by glouel** [comment]
Yeah I didn't update here, but FYI everyone, only 2 monitors is fixed (ish) in 13.4. 

And sadly I can report that 13.5beta 1 isn't any better for 3+ confirurations :( 

I have bugs opened with Apple around these, I updated those again, they seem to be aware of them... let's hope they get to finally fix it.

**Comment by glouel** [comment]
I'm closing this, please refer to these issue for more information : 

- Ventura (3 monitors still broken in 13.5beta4) : https://github.com/JohnCoates/Aerial/issues/1286

- Sonoma (2 monitors broken in beta2, everything kinda broken) : https://github.com/JohnCoates/Aerial/issues/1305
