### ISSUE TITLE
Display name of Login Item needs adjusting

### ISSUE THREAD

**Issue by sshultz** [AerialScreensaver/Aerial#57]
On macOS 13.3.1 (a) under "System Settings", "General", "Login Items", Aerial Companion shows under the "Allow in the Background" section as "Guillaume Louel".  It almost had me scanning for malware until I realized what it was.  It might be more appropriate to display "Aerial Companion" or "Aerial" here.

**Comment by glouel** [comment]
Hi @sshultz 

Please see this one : https://github.com/AerialScreensaver/AerialCompanion/issues/50 

I'm closing yours as a duplicate, feel free to comment on the other one if needed
