### ISSUE TITLE
Aerial Companion 1.2.2 Only Works with One Display on macOS Sonoma

### ISSUE THREAD

**Issue by rckingsley** [AerialScreensaver/Aerial#58]
I recently updated from macOS Ventura to macOS Sonoma.  I have a MacBook Pro with an external monitor.

On Ventura, Aerial Companion showed different scenes on each of my displays (seriously cool!).  However, with Sonoma, it only shows a scene on the laptop display - the external monitor is black.  When I click on the external display, I see an Apple 'Lock Screen' (showing the date and [in big numbers] the time of day) and a place at the bottom for me to enter my device password.

Obviously Sonoma is very new, but thought you would want to know before Sonoma goes public.

**Comment by glouel** [comment]
@rckingsley this can get a bit complicated as Companion can do a few things, and Sonoma adds stuff on top,so just to be sure, you are saying Companion shows different scenes on each on your display when you do what exactly ? 

From your description, you are talking about the screensaver part of Aerial ? 

If so, yes, sadly, this is bugged in Sonoma beta1 for 2 monitors configuration, it's an Apple bug, you can find more information here : https://github.com/JohnCoates/Aerial/issues/1305

There's a link at the bottom of the thread with some info I got from Apple (long story short, they know, they will fix it "sometimes"). 2 monitors may get fixed in beta2 or 3 though.

**Comment by glouel** [comment]
And you should try this beta of Companion : https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.5.0b3/Aerial.Companion.app.zip

1.2.2 will have stuff not working. I absolutely need to make that the new version of Companion, just a mess with all the macOS bugs.

**Comment by rckingsley** [comment]
Thank you for the quick response.  Yes, I was talking about the screen saver.  When I was running Ventura, each screen had a different ‘movie’ (very impressive!).  When I put on Sonoma, that didn’t work anymore.Obviously this is not a big deal for me, but I felt that you might want to know about it (apparently you do - which is great) before Sonoma is released to the public.Your response is very-much appreciated, and I look forward to when some of the Sonoma bugs are worked out and your product can work as it was designed.  You have an excellent program!Rick Kingsley___________________________________On Jun 14, 2023, at 3:54 PM, Guillaume Louel ***@***.***> wrote:
@rckingsley this can get a bit complicated as Companion can do a few things, and Sonoma adds stuff on top,so just to be sure, you are saying Companion shows different scenes on each on your display when you do what exactly ?
From your description, you are talking about the screensaver part of Aerial ?
If so, yes, sadly, this is bugged in Sonoma beta1 for 2 monitors configuration, it's an Apple bug, you can find more information here : JohnCoates/Aerial#1305
There's a link at the bottom of the thread with some info I got from Apple (long story short, they know, they will fix it "sometimes"). 2 monitors may get fixed in beta2 or 3 though.

**Comment by glouel** [comment]
@rckingsley sorry missed your reply. Apple broke 2 monitors in Sonoma, both in beta 1 and (differently) in beta2, I suggest you refer to this thread for more information : https://github.com/JohnCoates/Aerial/issues/1305

I'll close this one, please track the other for changes, but long story short, it's an Apple bug.
