### ISSUE TITLE
Automatically restart desktop background mode after reboot if running before reboot

### ISSUE THREAD

**Issue by raylau1234** [AerialScreensaver/Aerial#59]
Minor:

After a reboot, Companion starts up (as a login item), but it does not automatically restart the desktop background mode that was running before the reboot.

Running 1.5.0b3 on Ventura 13.4

**Comment by glouel** [comment]
Hey @raylau1234 

That's a good point ! I'm currently rethinking desktop background to handle multiple monitors and this is another thing that I definitely need to add so that the experience is a lot more seemless. 

I'll keep it in mind, thanks !

**Comment by glouel** [comment]
Hey @raylau1234 

This is in 1.5.0b4 : 

![Capture d’écran 2023-06-20 à 19 12 53](https://github.com/AerialScreensaver/AerialCompanion/assets/37544189/6629f189-9b61-4ac7-ab4a-3af732651ea5)

It will only restart if it was previously running. Also I suggest in that same window, you make sure get aerial beta says Yes. 

Of note, you can now quickly change the background video speed : 
![Capture d’écran 2023-06-20 à 19 14 45](https://github.com/AerialScreensaver/AerialCompanion/assets/37544189/e4d0b249-1658-4cc9-8991-766040dcf104)

Goes in steps: 1/8, 1/4, 1/3, 1/2, 2/3, and 1x speed. Those are calculated to work "fine" with both 24 fps videos and 240 fps videos. 240 fps support is added also in 3.2.7beta1, but note that only a handful of videos are currently available in that format (it will revert to 4K HEVC when not available).

**Comment by raylau1234** [comment]
The restart at launch works great!!!

However, fwiw, the speed setting doesn't work for my custom local video which is at 24 fps.

**Comment by glouel** [comment]
Speed should work with all videos, bit weird. 

You may need to restart Companion and make sure you updated to 3.2.7beta1 too. Let me know if it still doesn't. 

Edit: Double checked with a custom folder and it works here. One thing of note, you may need to reset the speed manually when video changes or at start, there's a bug around there.

**Comment by raylau1234** [comment]
Ah, it was an older version of aerial itself s I didn't have betas activated in companion.  Works now!
