### ISSUE TITLE
Newer than 1.4.0beta2 does not start up

### ISSUE THREAD

**Issue by craftey** [AerialScreensaver/Aerial#60]
Hi, I tried AerialCompanion.

Any version from 1.5.0b1 - 1.5.0b4 does not start up when starting normally via Finder. I can see the install wizzard for around 0.1 seconds. Then the app is closed.
When running via Terminal I get the following output also the app does not start.
```
$ /Users/me/Applications/Aerial\ Companion.app/Contents/MacOS/Aerial\ Companion 
update
Trace/BPT trap: 5
```

Version 1.4.0beta2 works just fine.

I also found a diagnostic report:
[Aerial Companion-2023-06-20-225609.ips.zip](https://github.com/AerialScreensaver/AerialCompanion/files/11807525/Aerial.Companion-2023-06-20-225609.ips.zip)

**Comment by glouel** [comment]
That's weird, can you try putting it in your /Applications folder instead, not your user one ? 

The log is weird too, I can't really see what is crashing. 

I haven't tested it recently on 12.6 there could be something I missed with backward compatibility, I'll try to have a look.

**Comment by glouel** [comment]
Can confirm the crash on 12, I'll try to investigate and get back to you.

**Comment by glouel** [comment]
@craftey I believe I fixed it in beta5, can you confirm when you have a sec ? Thanks !

https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.5.0b5/Aerial.Companion.app.zip

**Comment by craftey** [comment]
Hi @glouel , sorry for the late reply. Meanwhile I have upgraded to 13. So I cannot test on 12. However on 13 it works. 
I tried it on another Mac (intel instead of arm) with macOS 12. There it seems to work. Though I had to skip the wizard which selects the update method. Selecting an option would immediately crash. But closing the wizard let me proceed.
