### ISSUE TITLE
Cannot unlock under Sonoma beta 2/3

### ISSUE THREAD

**Issue by aemadrid-twx** [AerialScreensaver/Aerial#63]
# In Sonoma I cannot unlock - have to restart the machine

When I click the lock button on the Aerial Companion app the screensaver starts up but there is nothing I can click or type to mkae it unlock. If I hit the power button once I can present the login screen but after login in the lock is still there. I need to restart the machine fully to make it stop.

**Comment by glouel** [comment]
@aemadrid-twx I would need a bit more details, specifically : 
- Which version of Aerial Companion
- Your mac model
- How many monitors total, and on how many are you running Aerial ? 
- Does that happen if you launch Aerial via say a hot corner ?

Some old versions of Companion used to use a private API to launch the screen saver, I can see that being an issue maybe ? Barring that, I'm running Sonoma beta2 and so do a few people I know and haven't heard of that issue. In general the lock screen is not part of the screen saver but fully controlled by macOS, so having the lock screen bug is usually unrelated.

Anyway, if you don't already, first thing first, get the latest beta of Companion : https://github.com/AerialScreensaver/AerialCompanion/releases/tag/v1.5.0b7

**Comment by glouel** [comment]
You know what, scratch my previous comment, I double checked and can absolutely confirm your issue. I'll try to investigate tomorrow. Crazy thing is, I *thought* that the way Companion currently calls the screen saver was supposed to be safer, obviously it isn't. 

So thanks for the report, I'll dig into it and keep you posted !

**Comment by aemadrid-twx** [comment]
Thanks for checking it out. Just in case it helps I'm running on Sonoma Beta 3 (happenned on Beta 2 too), AC Version 1.5.0b7, with two monitors on a Mac Mini M2 Pro.

**Comment by glouel** [comment]
@aemadrid-twx again, thanks a whole lot for reporting this. 

I digged a bit more and it looks like the "classic" way to launch the screensaver fails now, but using the "unsafe" private API from Apple still works perfectly, I'll be releasing beta8 with that fix in a bit.

Again, many thanks as I had completely missed *that* bug. 

Edit : Reported as FB12542012, in case someone hits the same issue, I was using the accepted answer from here : https://stackoverflow.com/questions/4505198/how-can-i-start-the-screensaver-and-lock-the-screen-from-the-os-x-terminal which no longer works. 

Edit 2 : Pressing power twice let me log in back, I had watch unlock configured, I'm not sure if that changed anything. In any case that's not a proper workaround.

**Comment by glouel** [comment]
@aemadrid-twx please try https://github.com/AerialScreensaver/AerialCompanion/releases/tag/v1.5.0b8 and let me know, I believe this is fixed in that release.

**Comment by aemadrid-twx** [comment]
@glouel, this works great! It does launch the screensaver just like you would expect, and you can get out of it the same way. Thanks!
