### ISSUE TITLE
Is version 1.5.0b9 a beta or a stable release? 

### ISSUE THREAD

**Issue by suschizu** [AerialScreensaver/Aerial#65]
hello - the latest version is marked as "latest" which normally means it's a stable release but the description says that it's still a beta version … can someone clarify? thanks

**Comment by glouel** [comment]
Yeah sorry, I didn't think I would confuse everyone is this. Per the other thread, 1.2.2 is severly outdated and this is "stable" enough for me to have it as the latest release for everyone.

**Comment by suschizu** [comment]
thanks for the answer!
