### ISSUE TITLE
"Aerial" in macOS Sonoma vs "Aerial Companion"? 

### ISSUE THREAD

**Issue by jiagengliu** [AerialScreensaver/Aerial#69]
This is a clarifying question: what is the difference between Aerial here (Aerial Companion) and Aerial built into macOS 14.0 Sonoma? Should I run both? Can I use the purchased videos in the macOS version? Does the macOS version support showing temperature and time? Thanks.

**Comment by glouel** [comment]
Hey there

To clarify : 

- Aerial itself is the screen saver
- Aerial Companion serves as an installer/updater/extra features (to run the screen saver as your desktop background)

All the features (but desktop background) are part of the screensaver itself so if you want, you can just use the .saver. All installation options are explained here : https://aerialscreensaver.github.io/installation.html

**Comment by jiagengliu** [comment]
Thanks, but I wanted to know if the new Aerial screen saver built into **macOS Sonoma** works with Aerial Companion. Do you know if I can use the purchased videos in the macOS version? Can I show the temperature and time in the macOS version?

**Comment by glouel** [comment]
No, whatever is built into Sonoma is purely independant of this project. Unfortunately, Apple is reusing the Aerial name from this project, and that causes confusion. This is unfortunate, and I need to find a way to make sure people aren't confused about it (Apple certainly didn't help there). 

So no, you can't use any other video with the built in macOS stuff, nor show weather or anything else. The macOS version has none of the extra features that this project brings.

**Comment by jiagengliu** [comment]
Thank you!
