### ISSUE TITLE
Need to keep manifest.json up to date

### ISSUE THREAD

**Issue by stevehoek** [AerialScreensaver/Aerial#7]
It is lagging behind ... 2.0.2 of Saver was just released, but Companion was not updated.
Suggest the tool use the GitHub release feed to determine latest version so you don't have to keep updating this manifest file everytime you update Saver

**Comment by ZV00** [comment]
Yeah I can confirm that this issue is persisting here. I'll ping @glouel and let him know to take a look at your idea as well. Sounds like a good shortcut here!

**Comment by glouel** [comment]
It's fixed now sorry !
