### ISSUE TITLE
Sonoma 14.0: Latest (1.5.1) Companion says Screen Saver is disabled when (only) Sleep Screen is disabled

### ISSUE THREAD

**Issue by halfbrilliant** [AerialScreensaver/Aerial#70]
Enabling a time for powering off the display removes the notice, and disabling the power off brings it back, FWIW. If this is intentional then different language might be more suitable?  

<img width="475" alt="Screenshot 2023-10-06 at 16 28 40" src="https://github.com/AerialScreensaver/AerialCompanion/assets/60409194/ae8729c4-f173-4586-ad46-8bd7bb38cb47">

**Comment by glouel** [comment]
Looks like a bug on my end, I'll have a look and get back to you. 

Your configuration should not trigger that notice.

**Comment by glouel** [comment]
@halfbrilliant ok can confirm, thanks for the report, this is fixed for next version  : 

![Capture d’écran 2023-10-06 à 17 49 47](https://github.com/AerialScreensaver/AerialCompanion/assets/37544189/31796702-1452-4238-ac69-9c80cee27f77)

I may only release it this week end though as this is not extremely critical and I have a couple of other things still in flux for next release. Thanks again!

**Comment by glouel** [comment]
@halfbrilliant this should be fixed in 1.5.2, please install this : https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.5.2/Aerial.Companion.zip
