### ISSUE TITLE
Setting the Wallpaper works as expected, whilst the Screen Saver shows as just plain Black | Sonoma 14.1.1

### ISSUE THREAD

**Issue by andimandi1337** [AerialScreensaver/Aerial#72]
I have been trying to use Aerial as a way to set a mp4/mov file as my wallpaper and Screensaver. 
However as soon as I set the Aerial Screen Saver as default in Systemsettings, only the Wallpaper changes to the in Aerial Companion defined Videos/Screensavers, the Screensaver itself becomes plain black.
The Preview in System Settings also shows a plain Black Preview. 

Since Im not using one of the Preset Files, is there any Documentation on what requirements there are for importing your own Files into Aerial Companion?

**Comment by glouel** [comment]
Hi @andimandi1337 

Can you make a screenshot of this screen ? Make sure you scroll down so I can see your custom source fully : 

![Capture d’écran 2023-11-14 à 15 38 14](https://github.com/AerialScreensaver/AerialCompanion/assets/37544189/bb2c2c21-3eb3-4a68-9785-724ee398a411)

A few things could be happening but it's likely you skipped the instructions about where your files should be. The screen saver cannot access your personal files (desktop, documents, etc) because of macOS security restrictions, so I highly recommend to create a folder in `/Users/Shared/` and add this. Remove your old source first. 

Let me know if this was that

**Comment by andimandi1337** [comment]
First of all, thanks for the quick response! I've attached a screenshot below. The video files do play as they are supposed to, but only as desktop-background. The Screensaver Preview also does show the correct Video, but as soon as I actually enter the Screensaver, I either get the default "Horizon in Sonoma" Background (might be called something, since my systemlanguage isnt english) or just plain black. So it seems to me, that the problem lies in actually changing the Screensaver. 

<img width="1144" alt="Bildschirmfoto 2023-11-14 um 15 46 37" src="https://github.com/AerialScreensaver/AerialCompanion/assets/91610558/d8a81906-3b3b-4d6c-bbdd-5aa2006f2e99">

**Comment by andimandi1337** [comment]
First of all, thanks for the quick response! I've attached a screenshot below. The video files do play as they are supposed to, but only as desktop-background. The Screensaver Preview also does show the correct Video, but as soon as I actually enter the Screensaver, I either get the default "Horizon in Sonoma" Background (might be called something slightly different, since my systemlanguage isnt english) or just plain black. So it seems to me, that the problem lies in actually changing the Screensaver.

<img width="1144" alt="Bildschirmfoto 2023-11-14 um 16 06 58" src="https://github.com/AerialScreensaver/AerialCompanion/assets/91610558/383d2deb-099a-46f6-b4f3-4bab3c17685f">

**Comment by andimandi1337** [comment]
I was able to narrow it down a little further. The Problem only occurs, if i either close my macbook or induce Screensaver through CMD+Ctrl+Q. If the ScreenSaver activates through the timer defined in System Settings (e.g. 1min) everything works just fine.

**Comment by glouel** [comment]
I see, there are two separate things here : 

- The screen saver, it starts if you set a hot corner, wait the time, or use "Suspend activity" in macOS main menu (see below in french for it's position in the menu) : 
 
![Capture d’écran 2023-11-14 à 16 27 35](https://github.com/AerialScreensaver/AerialCompanion/assets/37544189/79dc3aae-ef69-4788-b9c4-17e0634848c4)

- The lock screen : The lock screen in macOS is separate from the screensaver, the screen saver on macOS will run for a period of time, before your mac goes to sleep (again, depending on settings). When you wake up your mac, you will not see the screen saver, but the default lock screen (which happens to be your default wallpaper). Pressing Cmd + ctrl + Q immediately locks the screen without starting the screensaver. 

So what you want is to set an image from your video (take a screenshot) and set it as your desktop background in macOS's System Settings. You can't put a video yourself there for now on the lock screen. And don't use cmd + ctrl +Q but use "Suspend Activity". If you use companion the very first icon will also immediately launch the screen saver for you : 

![Capture d’écran 2023-11-14 à 16 31 08](https://github.com/AerialScreensaver/AerialCompanion/assets/37544189/1f89473f-f81d-468f-876f-776bf279d064)

Makes sense ?

**Comment by andimandi1337** [comment]
Ok Great! Thank you for that explanation, turns out I just didn't know there was such a difference. 
Thanks a lot! :)

**Comment by glouel** [comment]
No worries ! A long time ago, you could mess with macOS and put a screen saver as your lock screen too, but Apple killed that (at least 5/6 years ago). 

And with Sonoma they  reintroduced it, but just for them, not for third parties yet. Maybe next year. Take care !
