### ISSUE TITLE
Not Working on Mac OS 10.14.6???

### ISSUE THREAD

**Issue by brianfos** [AerialScreensaver/Aerial#74]
I just updated from v1.2.2 to v1.5.2 on Mac OS 10.14.6. Everything worked under 1.2.2, but with 1.5.2, I get only a couple of options, as shown in the screen shot attached.
![Aerial Companion Pull-Down Menu](https://github.com/AerialScreensaver/AerialCompanion/assets/24682824/2c41a57e-2cdd-41a5-ba20-bd44d07c7a98)

**Comment by glouel** [comment]
@brianfos it's hard for me to support every single macOS version and 10.14 is extremely outdated at this point, so yeah you are missing the icons right now. 

I would recommend sticking to 1.2.2 until you upgrade to a newer version of macOS (or try looking into OpenCore to run more modern macOS on unsupported hardware).
