### ISSUE TITLE
Overlays not working on MacOS Sonoma

### ISSUE THREAD

**Issue by dlward50** [AerialScreensaver/Aerial#75]
As soon as I upgraded to Sonoma, Aerial started acting differently.  I cannot choose different scenes for each screen and there are no overlays (weather, clock or scene description etc.) even though I have enabled them.  My other Macs with earlier OS versions are working fine so it must be a Sonoma problem.  I just upgraded to 3.3.5 but the problem still exists.  Hopefully this is something you're aware of and working on.  Love the program more than I love Sonoma.  

Thanks,

Dan Ward
dlward50@gmail.com

**Comment by glouel** [comment]
Hi @dlward50 

What likely happens is that for most people, Sonoma deactivates their screensaver and replaces it with "their" thing. So what you need to do is enable Aerial again. Follow these steps : 

![Capture d’écran 2023-11-06 à 00 55 01](https://github.com/AerialScreensaver/AerialCompanion/assets/37544189/538676a1-a5de-46eb-8566-a866632c07d5)

You need to scroll down the list and go full right to see Aerial, click it, make sure it shows everything like my arrows on the screenshot, and you'll be good to go. The videos you see in the middle is Apple's new screensaver thing, and not Aerial. They couldn't made it more confusing for someone who used Aerial before 😩

**Comment by dlward50** [comment]
Guillaume,

Wow, thanks for getting back to me so quickly.  I’ll try that tomorrow.

Dan


***@***.*** Bene vive, saepe ride, multum ama

**Comment by dlward50** [comment]
Thanks Guillame.  It works as before now!  Keep up the good work!  Bought
you a coffee as well.  Enjoy!

Dan

***@***.*** Bene vive, saepe ride, multum ama
