### ISSUE TITLE
wallpaper only works on 1 display

### ISSUE THREAD

**Issue by peterchabs** [AerialScreensaver/Aerial#77]
Aerial Screensaver spans across both of my displays nearly perfect after adjusting some alignment settings under 'Advanced' (LG Ultrawide Monitor + MacBook Air M1 2020), but I can't get Aerial Wallpaper to do the same for whatever reason. I am stuck only using the wallpaper on 1 display.

**Comment by glouel** [comment]
Hey @peterchabs 

Which version of Companion are you using ? I remember fixing that a few months back. Make sure you have latest (1.5.2). 

If not let me know.

**Comment by peterchabs** [comment]
Ahh that's embarrassing, I was apparently on an old beta release. I received an in-app notification that an update was available the other day and I assumed after that I was on the latest. 

All updated now, thank you.

**Comment by glouel** [comment]
No worries, for (mostly wrong) reasons I don't notify when new versions of Companion are released. Backward compatibility can be problematic on old OSes but I think I should just get on with it and push the latest to everyone 😅
