### ISSUE TITLE
When launching Desktop background, it starts only on one display (1 of 2) the one I clicked Start on (beta 1.4)

### ISSUE THREAD

**Issue by incline02** [AerialScreensaver/Aerial#79]
Hello Guillaume

The beta version seems to work solely on one display despite having it set up to "Pan over all display" in Aerial settings and "Show on all spaces" in Wallpaper and ScreenSaver settings of macOS.

really appreciate your work. let me know if you want to link up on linden, happy to beta test for you, I speak French and am a User Researcher

**Comment by glouel** [comment]
En français alors, salut !

La 1.4 ne supporte pas le multi-monitor en mode desktop, installe la 1.5.2 : https://github.com/AerialScreensaver/AerialCompanion/releases/tag/v1.5.2

**Comment by incline02** [comment]
je comprends pas pourquoi j'ai téléchargé une version passée! merci pour ta réponse, ta rapidité et ton travail!
