### ISSUE TITLE
Not updating to Aerial new build 2.0.2?

### ISSUE THREAD

**Issue by DrMORO617** [AerialScreensaver/Aerial#8]
Hi!
By AerialCompanion menubar app, clicked Check Now... after receiving email about 2.0.2 update, but says "No new version available" somehow. Not sure if any other setting would matter, but tried to change a few, yet still no new version found.
Love to concept, so hope there is a fix.
Thanks!

**Comment by ZV00** [comment]
Hey @DrMORO617,

Yeah there was a hiccup in this update. As mentioned in #7 the issue should be resolved now. Go ahead and click "Check Now" again.

**Comment by DrMORO617** [comment]
WOW! That was really quick! Just like in seconds!
Thanks! I was able to update to 2.0.2.
Case closed!
