### ISSUE TITLE
Aerial Companion not working on macOS Sequoia 15.0.1 

### ISSUE THREAD

**Issue by lafllamme** [AerialScreensaver/Aerial#86]
Aerial Companion is not functioning on macOS Sequoia 15.0.1. After opening, it disappears without displaying any icon in the menu bar. This issue persists even after moving the app to the Applications folder.

System Information:

    macOS: Sequoia 15.0.1
    Device: MacBook Pro 16" (2021)
    Chip: Apple M1 Pro
    Memory: 16 GB

Steps to Reproduce:

    Download and open Aerial Companion.
    Move to the Applications folder.
    Launch the app.

Expected Behavior:
An icon should appear in the menu bar, and the app should remain open for use.

Actual Behavior:
No icon appears in the menu bar, and the app closes immediately after the first launch.

**Comment by glouel** [comment]
Hey @lafllamme 

Did you have it installed previously or is it a fresh install ? I haven't seen that particular issue reported, and it's running fine for a bunch of people in 15.0/.1/.2 beta so far. 

It does have a mechanism to run periodically if you don't want it in your menu bar, but you have to ask for that explicitly in settings. So maybe some corrupted settings or something from a previous install ?

**Comment by lafllamme** [comment]
Hey @glouel 

I did have it installed on Sonoma (14.0+), updated my MacBook to Sequioa 15.0.1, then removed it and now I’m aiming for a completely fresh install. Could you let me know which internal paths I need to delete for a thorough removal and re-install?

Also, are there any additional files or apps I should download for this setup, like the Aerial files from [this link](https://github.com/JohnCoates/Aerial) (afaik I do not have to separetely download the aerial screen saver file - even with it didnt launch ?)

I tried to uninstall data from these paths:


```
    ~/Library/Screen Savers/
    ~/Library/Caches/Aerial/
    ~/Library/Application Support/Aerial/
    ~/Library/Preferences/ (search for any files named com.JohnCoates.Aerial.plist or com.glouel.AerialUpdater.plist)
    ~/Library/Logs/ (if any Aerial logs exist here)
```
    

Thanks!

**Comment by glouel** [comment]
Sorry for the late reply. 

For Companion and your bug precisely : 

If you haven't deleted preferences, in Terminal do : 

```
defaults delete com.glouel.AerialUpdater
```

This will reset Companion's preferences. You can also delete '~/Library/Application Support/AerialUpdater' to make it totally fresh, but quite frankly it should not matter, it's just logs and temporary files. 

If you did delete that file, run the command anyway, but you probably need to restart your mac afterwards (macOS has a cache for preferences, deleting the plist isn't enough and doing it manually messes with things). You can try to launch Companion and if it doesn't work still, run the command again, and restart your mac. Companion should then work and prompt you with this : 

![Screenshot 2024-10-29 at 15 19 41](https://github.com/user-attachments/assets/c6191167-c05d-4637-a32c-8ccadadf8658)

If you want to fully reset the screensaver : 

```
defaults delete ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/com.glouel.Aerial.plist
```

To wipe all screensaver data, wipe this folder : 

`~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial`

This will make you start fresh. You don't need to install anything bug Companion, it will prompt you to install the screensaver for you. 

Let me know how it goes.

**Comment by lafllamme** [comment]
Hi @glouel,

Thanks for the quick response! That worked perfectly—it looks like I had some corrupted or old files causing the issue. Companion is up and running now, and I’m happy to have those beautiful backgrounds back while coding.

This might be a good tip to add to the documentation or FAQ in case others run into the same problem. Thanks again for the fast support and great work!

**Comment by glouel** [comment]
No worries and yes it's on me, the doc is awfully outdated and the old instructions don't work. I'll try to set aside some time this week end to update it !
